name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^3.2.0
  nuvigator:
    path: ../

dev_dependencies:
  build_runner: ^1.5.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
