name: nuvigator
description: A powerful routing abstraction over Flutter navigator, providing some new features and an easy way to define routers.
version: 1.2.1

homepage: https://github.com/nubank/nuvigator

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  analyzer: ^1.5.0
  build: ^2.0.1
  build_config: ^1.0.0
  code_builder: ^4.0.0
  dart_style: ^2.0.1
  flutter:
    sdk: flutter
  path_to_regexp: ^0.4.0
  recase: ^4.0.0
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8
  pedantic: ^1.11.0
