name: nuvigator
description: A powerful routing abstraction over Flutter navigator, providing some new features and an easy way to define routers.
version: 1.0.0

homepage: https://github.com/nubank/nuvigator

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  analyzer: ^1.5.0
  build: ^2.0.1
  build_config: ^1.0.0
  code_builder: ^3.2.0
  dart_style: '>=1.2.9 <1.4.0'
  flutter:
    sdk: flutter
  path_to_regexp: ^0.3.0
  recase: '>=2.0.0 <3.1.0'
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^1.6.5
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: ^1.9.0
