name: nuvigator
description: A powerful and strongly typed routing abstraction over Flutter navigator, providing some new features and an easy way to define routers with code generation.
version: 0.2.0

homepage: https://github.com/nubank/nuvigator

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  build: '>=0.12.6 <2.0.0'
  build_config: '>=0.2.6 <0.5.0'
  code_builder: ^3.2.0
  source_gen: ^0.9.4+5
  analyzer: '>=0.37.1 <0.40.0'
  dart_style: ^1.3.3
  flutter:
    sdk: flutter
  path_to_regexp: ^0.3.0

dev_dependencies:
  mockito: ^4.1.1
  build_runner: ^1.6.5
  flutter_test:
    sdk: flutter
